#!/usr/bin/env bash
# Shared helpers for start.sh / stop.sh / status.sh

WEBAPP_TMUX_SESSION="${WEBAPP_TMUX_SESSION:-ultra-fast-rag-webapp}"
WEBAPP_BACKEND_PORT="${WEBAPP_BACKEND_PORT:-8000}"
WEBAPP_FRONTEND_PORT="${WEBAPP_FRONTEND_PORT:-5173}"
WEBAPP_BACKEND_URL="http://127.0.0.1:${WEBAPP_BACKEND_PORT}"
WEBAPP_FRONTEND_URL="http://127.0.0.1:${WEBAPP_FRONTEND_PORT}"

webapp_root() {
  local script_dir
  script_dir="$(cd "$(dirname "${BASH_SOURCE[1]:-${BASH_SOURCE[0]}}")" && pwd)"
  if [[ "$(basename "$script_dir")" == "lib" && "$(basename "$(dirname "$script_dir")")" == "scripts" ]]; then
    cd "$script_dir/../.." && pwd
    return
  fi
  cd "$script_dir/.." && pwd
}

webapp_is_pid_running() {
  local pid="${1:-}"
  [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null
}

webapp_read_pid_file() {
  local pid_file="$1"
  if [[ -f "$pid_file" ]]; then
    tr -d '[:space:]' <"$pid_file"
  fi
}

webapp_listener_pid() {
  local port="$1"
  lsof -nP -iTCP:"$port" -sTCP:LISTEN -t 2>/dev/null | head -n 1
}

webapp_is_port_listening() {
  local port="$1"
  webapp_listener_pid "$port" >/dev/null
}

webapp_wait_for_port() {
  local port="$1"
  local timeout_s="${2:-20}"
  local waited=0
  while (( waited < timeout_s )); do
    if webapp_is_port_listening "$port"; then
      return 0
    fi
    sleep 1
    waited=$((waited + 1))
  done
  return 1
}

webapp_curl_ok() {
  local url="$1"
  local timeout_s="${2:-5}"
  curl -fsS --max-time "$timeout_s" "$url" >/dev/null 2>&1
}

webapp_kill_port() {
  local port="$1"
  local label="$2"
  local pids pid
  pids="$(lsof -nP -iTCP:"$port" -sTCP:LISTEN -t 2>/dev/null || true)"
  [[ -n "$pids" ]] || return 0
  while IFS= read -r pid; do
    [[ -n "$pid" ]] || continue
    kill "$pid" 2>/dev/null || true
    sleep 1
    if webapp_is_pid_running "$pid"; then
      kill -9 "$pid" 2>/dev/null || true
    fi
    echo "Stopped $label listener on port $port (PID $pid)"
  done <<<"$pids"
}

webapp_kill_uvicorn_tree() {
  pkill -f "uvicorn src.scrape_planner.webapp.api:app" 2>/dev/null || true
}

webapp_kill_vite_tree() {
  pkill -f "vite --host 127.0.0.1 --port ${WEBAPP_FRONTEND_PORT}" 2>/dev/null || true
}

webapp_tmux_available() {
  command -v tmux >/dev/null 2>&1
}

webapp_tmux_has_session() {
  webapp_tmux_available && tmux has-session -t "$WEBAPP_TMUX_SESSION" 2>/dev/null
}

webapp_write_env_file() {
  local env_file="$1"
  local data_root="$2"
  mkdir -p "$(dirname "$env_file")"
  cat >"$env_file" <<EOF
# Generated by start.sh — do not edit while services are running.
SCRAPE_PLANNER_DATA_ROOT=$data_root
WEBAPP_BACKEND_PORT=$WEBAPP_BACKEND_PORT
WEBAPP_FRONTEND_PORT=$WEBAPP_FRONTEND_PORT
# Reload blocks shutdown while SSE clients are connected; default off for ./start.sh.
WEBAPP_RELOAD=${WEBAPP_RELOAD:-0}
EOF
}

webapp_backend_command() {
  local root="$1"
  printf 'cd %q && source .venv/bin/activate && set -a && source %q && set +a && exec ./scripts/run-webapp.sh' \
    "$root" "$root/logs/webapp.env"
}

webapp_frontend_command() {
  local root="$1"
  printf 'cd %q/frontend && exec npm run dev' "$root"
}

webapp_ensure_tmux_session() {
  local root="$1"
  local backend_cmd frontend_cmd
  backend_cmd="$(webapp_backend_command "$root")"
  frontend_cmd="$(webapp_frontend_command "$root")"

  if webapp_tmux_has_session; then
    return 0
  fi

  tmux new-session -d -s "$WEBAPP_TMUX_SESSION" -n backend "$backend_cmd"
  tmux new-window -t "$WEBAPP_TMUX_SESSION" -n frontend "$frontend_cmd"
  tmux select-window -t "$WEBAPP_TMUX_SESSION:backend"
  echo "Created tmux session '$WEBAPP_TMUX_SESSION' (windows: backend, frontend)"
}

webapp_restart_tmux_window() {
  local window="$1"
  local command="$2"
  if ! webapp_tmux_has_session; then
    return 1
  fi
  if tmux list-windows -t "$WEBAPP_TMUX_SESSION" -F '#{window_name}' 2>/dev/null | grep -qx "$window"; then
    tmux respawn-window -t "$WEBAPP_TMUX_SESSION:$window" -k "$command"
  else
    tmux new-window -t "$WEBAPP_TMUX_SESSION" -n "$window" "$command"
  fi
}

webapp_start_via_tmux() {
  local root="$1"
  webapp_ensure_tmux_session "$root"
  if ! webapp_is_port_listening "$WEBAPP_BACKEND_PORT"; then
    webapp_restart_tmux_window backend "$(webapp_backend_command "$root")"
    echo "Starting backend in tmux:$WEBAPP_TMUX_SESSION:backend"
  else
    echo "Backend already listening on port $WEBAPP_BACKEND_PORT"
  fi
  if ! webapp_is_port_listening "$WEBAPP_FRONTEND_PORT"; then
    webapp_restart_tmux_window frontend "$(webapp_frontend_command "$root")"
    echo "Starting frontend in tmux:$WEBAPP_TMUX_SESSION:frontend"
  else
    echo "Frontend already listening on port $WEBAPP_FRONTEND_PORT"
  fi
}

webapp_start_via_nohup() {
  local root="$1"
  local log_dir="$root/logs"
  local backend_log="$log_dir/webapp-${WEBAPP_BACKEND_PORT}.out"
  local frontend_log="$log_dir/frontend-${WEBAPP_FRONTEND_PORT}.out"
  local backend_pid_file="$log_dir/webapp-${WEBAPP_BACKEND_PORT}.pid"
  local frontend_pid_file="$log_dir/frontend-${WEBAPP_FRONTEND_PORT}.pid"

  if ! webapp_is_port_listening "$WEBAPP_BACKEND_PORT"; then
    nohup bash -lc "$(webapp_backend_command "$root")" >>"$backend_log" 2>&1 &
    disown $! 2>/dev/null || true
    echo "Launched backend via nohup (log: $backend_log)"
  fi

  if ! webapp_is_port_listening "$WEBAPP_FRONTEND_PORT"; then
    nohup bash -lc "$(webapp_frontend_command "$root")" >>"$frontend_log" 2>&1 &
    disown $! 2>/dev/null || true
    echo "Launched frontend via nohup (log: $frontend_log)"
  fi

  if webapp_wait_for_port "$WEBAPP_BACKEND_PORT" 25; then
    local backend_pid
    backend_pid="$(webapp_listener_pid "$WEBAPP_BACKEND_PORT" || true)"
    [[ -n "$backend_pid" ]] && echo "$backend_pid" >"$backend_pid_file"
  fi
  if webapp_wait_for_port "$WEBAPP_FRONTEND_PORT" 25; then
    local frontend_pid
    frontend_pid="$(webapp_listener_pid "$WEBAPP_FRONTEND_PORT" || true)"
    [[ -n "$frontend_pid" ]] && echo "$frontend_pid" >"$frontend_pid_file"
  fi
}

webapp_verify_health() {
  local root="$1"
  local data_root="$2"
  local failures=0

  if ! webapp_wait_for_port "$WEBAPP_BACKEND_PORT" 25; then
    echo "ERROR: backend did not bind port $WEBAPP_BACKEND_PORT (see $root/logs/webapp-${WEBAPP_BACKEND_PORT}.out)" >&2
    failures=$((failures + 1))
  elif ! webapp_curl_ok "$WEBAPP_BACKEND_URL/api/health" 10; then
    echo "ERROR: backend health check failed at $WEBAPP_BACKEND_URL/api/health" >&2
    failures=$((failures + 1))
  fi

  if ! webapp_wait_for_port "$WEBAPP_FRONTEND_PORT" 25; then
    echo "ERROR: frontend did not bind port $WEBAPP_FRONTEND_PORT (see $root/logs/frontend-${WEBAPP_FRONTEND_PORT}.out)" >&2
    failures=$((failures + 1))
  elif ! webapp_curl_ok "$WEBAPP_FRONTEND_URL/" 10; then
    echo "ERROR: frontend check failed at $WEBAPP_FRONTEND_URL/" >&2
    failures=$((failures + 1))
  fi

  local site_count
  site_count="$(curl -fsS --max-time 10 "$WEBAPP_BACKEND_URL/api/sites" 2>/dev/null | python3 -c "import json,sys; print(len(json.load(sys.stdin).get('sites',[])))" 2>/dev/null || echo 0)"
  echo "Data root: $data_root"
  echo "Sites visible to API: $site_count"
  if [[ "$site_count" == "0" ]]; then
    echo "WARNING: no workspaces found under $data_root/sites — UI will show an empty state." >&2
  fi

  return "$failures"
}
